MbmStore/Controllers/NavController.cs
using MbmStore.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace MbmStore.Controllers
{
    public class NavController : Controller
    {
        Repository repository = new Repository();
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

MbmStore/Views/Shared/ProductSummaryBook.cshtml
@model MbmStore.Models.Book

<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">@Model.Title</h2>
        </div>
        <div class="panel-body">
            <div class="col-md-6">
                <img src="/Content/Images/@Model.ImageUrl" height="200" alt="@Model.Title" />
            </div>
            <div class="col-md-6">
                <div class="btn btn-default">
                    <h3>kr. @String.Format("{0:0.00}", Model.Price)</h3>
                </div>
                @using (Html.BeginForm("AddToCart", "Cart"))
                {
                    @Html.Hidden("ProductId", Model.ProductId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Add to cart" />
                }

                <p>
                    Author: @Model.Author<br>
                    Publisher: @Model.Publisher (@Model.Published)<br />
                    ISBN: @Model.ISBN<br />
                </p>
            </div>
        </div>
    </div>
</div>

MbmStore/Views/Shared/ProductSummaryMovie.cshtml
@model MbmStore.Models.Movie
@using MbmStore.Models

<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">@Model.Title</h2>
        </div>
        <div class="panel-body">
            <div class="col-md-6">
                <img src="/Content/Images/@Model.ImageUrl" alt="@Model.Title" />
            </div>
            <div class="col-md-6">
                <div class="caption">
                    <div class="btn btn-default">
                        <h4>kr. @String.Format("{0:0.00}", Model.Price)</h4>
                    </div>
                    @using (Html.BeginForm("AddToCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", Model.ProductId)
                        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                        <input type="submit" class="btn btn-success" value="Add to cart" />
                    }
                    <p><strong>Director:</strong> @Model.Director</p>
                </div>
            </div>
        </div>
    </div>
</div>

MbmStore/Views/Shared/ProductSummaryMusicCD.cshtml
@model MbmStore.Models.MusicCD
@using MbmStore.Models

<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">@Model.Title <small>@Model.Artist</small></h2>
        </div>
        <div class="panel-body">
            <div class="col-md-4">
                <img src="/Content/Images/@Model.ImageUrl" height="200" alt="@Model.Title" />
            </div>
            <div class="col-md-8">
                <div class="btn btn-default">
                    <h3>kr. @String.Format("{0:0.00}", Model.Price)</h3>
                </div>
                @using (Html.BeginForm("AddToCart", "Cart"))
                {
                    @Html.Hidden("ProductId", Model.ProductId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Add to cart" />
                }

                <p><i>Publisher: @Model.Label (@Model.Released)</i></p>
            </div>
            <div class="col-md-12">
                <h3>Tracklist</h3>
                <ol>
                    @foreach (Track t in Model.Tracks)
                    {
                        <li> @t.Title <i>(@t.Composer)</i> -- @t.Length.Minutes:@t.Length.Seconds</li>
                    }
                </ol>
                <p><strong>Total Play time: @Model.GetPlayingTime()</strong></p>
            </div>
        </div>
    </div>
</div>

MbmStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MBM Store - Front</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="~/Content/custom.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MBM Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/Catalogue">Catalogue</a></li>
                    <li><a href="/Invoice">Invoice</a></li>
                </ul>
            </div>
            <div class="checkout-widget">
                @Html.Action("Summary", "Cart")
            </div>
        </div>
    </div>

    <div>
        <div class="container-fluid">
            <div class="col-md-2">
                @Html.Action("Menu", "Nav")
            </div>
            <div class="col-md-10">
                @RenderBody()
            </div>
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Daniel, Christian & Rasmus</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>